/**
 * Salary Comparison Form Constants
 * 
 * Este archivo contiene todas las constantes utilizadas en el formulario de comparación salarial:
 * - Opciones de países
 * - Opciones de ocupaciones/profesiones
 * - Niveles de experiencia
 * - Labels de campos del formulario
 * - Configuración de pasos del wizard
 */

export const formSteps = [
    {
        id: "step-1",
        stepNumber: 1,
        title: "Step 1",
        fields: [
            {
                id: "country",
                type: "select",
                label: "Country",
                placeholder: "Choose your country",
                required: true,
                options: [
                    { label: "Austria", value: "austria", selected: false },
                    { label: "Belgium", value: "belgium", selected: false },
                    { label: "Bulgaria", value: "bulgaria", selected: false },
                    { label: "Croatia", value: "croatia", selected: false },
                    { label: "Cyprus", value: "cyprus", selected: false },
                    { label: "Czech Republic", value: "czech_republic", selected: false },
                    { label: "Denmark", value: "denmark", selected: false },
                    { label: "Estonia", value: "estonia", selected: false },
                    { label: "France", value: "france", selected: false },
                    { label: "Germany", value: "germany", selected: false },
                    { label: "Greece", value: "greece", selected: false },
                    { label: "Ireland", value: "ireland", selected: false },
                    { label: "Italy", value: "italy", selected: false },
                    { label: "Latvia", value: "latvia", selected: false },
                    { label: "Lithuania", value: "lithuania", selected: false },
                    { label: "Luxembourg", value: "luxembourg", selected: false },
                    { label: "Malta", value: "malta", selected: false },
                    { label: "Netherlands", value: "netherlands", selected: false },
                    { label: "Portugal", value: "portugal", selected: false },
                    { label: "Slovakia", value: "slovakia", selected: false },
                    { label: "Slovenia", value: "slovenia", selected: false },
                    { label: "Spain", value: "spain", selected: false },
                    { label: "Sweden", value: "sweden", selected: false },
                    { label: "United Kingdom", value: "united_kingdom", selected: false }
                ]
            },
            {
                id: "gender",
                type: "select",
                label: "Gender",
                required: true,
                options: [
                    { label: "Male", value: "male" },
                    { label: "Female", value: "female" },
                    { label: "Other", value: "other" }
                ]
            },
            {
                id: "monthlyWage",
                type: "number",
                label: "Monthly Wage (€)",
                required: true,
                placeholder: "Enter your monthly wage"
            }
        ]
    },
    {
        id: "step-2",
        stepNumber: 2,
        title: "Step 2",
        fields: [
            {
                id: "economicActivity",
                type: "select",
                label: "Economic Activity",
                placeholder: "Choose an economic activity",
                required: true,
                options: [
                    { label: "Accounting, bookkeeping and auditing activities; tax consultancy", value: "accounting_bookkeeping_auditing" },
                    { label: "Activities of call centres", value: "call_centres" },
                    { label: "Activities of collection agencies and credit bureaus", value: "collection_agencies" },
                    { label: "Activities of employment placement agencies", value: "employment_agencies" },
                    { label: "Activities of professional membership organisations", value: "professional_orgs" },
                    { label: "Activities of religious organisations", value: "religious_orgs" },
                    { label: "Activities of sports clubs", value: "sports_clubs" },
                    { label: "Administration of financial markets", value: "financial_markets" },
                    { label: "Artistic creation", value: "artistic_creation" },
                    { label: "Beverage serving activities", value: "beverage_serving" },
                    { label: "Business and other management consultancy activities", value: "management_consultancy" },
                    { label: "Buying and selling of own real estate", value: "real_estate_buying" },
                    { label: "Cargo handling", value: "cargo_handling" },
                    { label: "Central banking", value: "central_banking" },
                    { label: "Child day-care activities", value: "child_daycare" },
                    { label: "Combined office administrative service activities", value: "office_admin_services" },
                    { label: "Computer consultancy activities", value: "computer_consultancy" },
                    { label: "Computer facilities management activities", value: "computer_facilities" },
                    { label: "Computer programming activities", value: "computer_programming" },
                    { label: "Compulsory social security activities", value: "social_security" },
                    { label: "Construction of bridges and tunnels", value: "construction_bridges" },
                    { label: "Construction of roads and motorways", value: "construction_roads" },
                    { label: "Construction of residential and non-residential buildings", value: "construction_buildings" },
                    { label: "Data processing, hosting and related activities", value: "data_processing" },
                    { label: "Defence activities", value: "defence" },
                    { label: "Demolition and site preparation", value: "demolition" },
                    { label: "Development of building projects", value: "building_development" },
                    { label: "Distribution of electricity", value: "electricity_distribution" },
                    { label: "Electrical installation", value: "electrical_installation" },
                    { label: "Engineering activities and related technical consultancy", value: "engineering_consultancy" },
                    { label: "Extraction of crude petroleum", value: "crude_petroleum" },
                    { label: "Fitness facilities", value: "fitness_facilities" },
                    { label: "Foreign affairs", value: "foreign_affairs" },
                    { label: "Freight transport by road", value: "freight_transport" },
                    { label: "Fund management activities", value: "fund_management" },
                    { label: "General medical practice activities", value: "medical_practice" },
                    { label: "General public administration activities", value: "public_administration" },
                    { label: "General secondary education", value: "secondary_education" },
                    { label: "Growing of non-perennial crops", value: "non_perennial_crops" },
                    { label: "Growing of perennial crops", value: "perennial_crops" },
                    { label: "Hospital activities", value: "hospital_activities" },
                    { label: "Hotels and similar accommodation", value: "hotels_accommodation" },
                    { label: "Joinery installation", value: "joinery_installation" },
                    { label: "Legal activities", value: "legal_activities" },
                    { label: "Maintenance and repair of motor vehicles", value: "vehicle_maintenance" },
                    { label: "Management of real estate on fee or contract basis", value: "real_estate_management" },
                    { label: "Manufacture of base metals", value: "manufacture_base_metals" },
                    { label: "Manufacture of basic pharmaceutical products and pharmaceutical preparations", value: "pharmaceutical_manufacture" },
                    { label: "Manufacture of beverages", value: "beverage_manufacture" },
                    { label: "Manufacture of chemicals and chemical products", value: "chemical_manufacture" },
                    { label: "Manufacture of computer, electronic and optical products", value: "electronics_manufacture" },
                    { label: "Manufacture of electrical equipment", value: "electrical_equipment" },
                    { label: "Manufacture of fabricated metal products", value: "metal_products" },
                    { label: "Manufacture of food products", value: "food_manufacture" },
                    { label: "Manufacture of furniture", value: "furniture_manufacture" },
                    { label: "Manufacture of machinery and equipment", value: "machinery_manufacture" },
                    { label: "Manufacture of motor vehicles, trailers and semi-trailers", value: "motor_vehicles" },
                    { label: "Manufacture of other transport equipment", value: "transport_equipment" },
                    { label: "Manufacture of rubber and plastic products", value: "rubber_plastic" },
                    { label: "Manufacture of textiles", value: "textile_manufacture" },
                    { label: "Manufacture of wearing apparel", value: "apparel_manufacture" },
                    { label: "Manufacture of wood and products of wood and cork", value: "wood_manufacture" },
                    { label: "Missing (Mapping not available)", value: "missing" },
                    { label: "Motion picture, video and television programme production activities", value: "media_production" },
                    { label: "Motion picture, video and television programme post-production activities", value: "media_post_production" },
                    { label: "Museums activities", value: "museums" },
                    { label: "Mining of other non-ferrous metal ores", value: "mining_metals" },
                    { label: "Non-specialised wholesale trade", value: "wholesale_general" },
                    { label: "Operation of sports facilities", value: "sports_facilities" },
                    { label: "Organisation of conventions and trade shows", value: "conventions_trade" },
                    { label: "Other accommodation", value: "other_accommodation" },
                    { label: "Other activities auxiliary to financial services", value: "financial_auxiliaries" },
                    { label: "Other building and industrial cleaning activities", value: "building_cleaning" },
                    { label: "Other cleaning activities", value: "cleaning_activities" },
                    { label: "Other education", value: "other_education" },
                    { label: "Other human health activities", value: "health_activities" },
                    { label: "Other information technology and computer service activities", value: "it_services" },
                    { label: "Other manufacturing", value: "other_manufacturing" },
                    { label: "Other mining and quarrying", value: "other_mining" },
                    { label: "Other monetary intermediation", value: "monetary_intermediation" },
                    { label: "Other personal service activities", value: "personal_services" },
                    { label: "Other postal and courier activities", value: "postal_courier" },
                    { label: "Other professional, scientific and technical activities", value: "professional_technical" },
                    { label: "Other research and experimental development", value: "research_development" },
                    { label: "Other software publishing", value: "software_publishing" },
                    { label: "Other specialised wholesale", value: "wholesale_specialised" },
                    { label: "Other sports activities", value: "other_sports" },
                    { label: "Performing arts", value: "performing_arts" },
                    { label: "Physical well-being activities", value: "physical_wellbeing" },
                    { label: "Post-secondary non-tertiary education", value: "post_secondary_education" },
                    { label: "Publishing of journals and periodicals", value: "journals_publishing" },
                    { label: "Publishing of newspapers", value: "newspapers_publishing" },
                    { label: "Recovery of sorted materials", value: "materials_recovery" },
                    { label: "Regulation of health care, education and social services", value: "social_regulation" },
                    { label: "Repair and installation of machinery and equipment", value: "machinery_repair" },
                    { label: "Residential care activities", value: "residential_care" },
                    { label: "Restaurants and mobile food service activities", value: "restaurants" },
                    { label: "Retail sale in non-specialised stores", value: "retail_general" },
                    { label: "Retail sale of automotive fuel", value: "retail_fuel" },
                    { label: "Retail sale of clothing", value: "retail_clothing" },
                    { label: "Retail sale of cosmetics and toilet articles", value: "retail_cosmetics" },
                    { label: "Retail sale of flowers, plants, seeds", value: "retail_flowers" },
                    { label: "Retail sale of food, beverages and tobacco", value: "retail_food" },
                    { label: "Retail sale of footwear and leather goods", value: "retail_footwear" },
                    { label: "Retail sale of furniture and household articles", value: "retail_furniture" },
                    { label: "Retail sale of medical and orthopaedic goods", value: "retail_medical" },
                    { label: "Retail sale of newspapers and stationery", value: "retail_stationery" },
                    { label: "Retail sale of second-hand goods", value: "retail_secondhand" },
                    { label: "Retail sale of sporting equipment", value: "retail_sporting" },
                    { label: "Retail sale of textiles", value: "retail_textiles" },
                    { label: "Retail sale of watches and jewellery", value: "retail_jewellery" },
                    { label: "Retail sale via mail order or internet", value: "retail_online" },
                    { label: "Retail sale via stalls and markets", value: "retail_markets" },
                    { label: "Retail trade of motor vehicle parts and accessories", value: "retail_vehicle_parts" },
                    { label: "Roofing activities", value: "roofing" },
                    { label: "Sale of cars and light motor vehicles", value: "sale_cars" },
                    { label: "Sale of other motor vehicles", value: "sale_vehicles" },
                    { label: "Sea and coastal passenger water transport", value: "water_transport" },
                    { label: "Service activities incidental to land transportation", value: "transportation_services" },
                    { label: "Social work activities for the elderly and disabled", value: "social_work" },
                    { label: "Specialist medical practice activities", value: "specialist_medical" },
                    { label: "Support activities to agriculture", value: "agriculture_support" },
                    { label: "Support activities to performing arts", value: "arts_support" },
                    { label: "Technical testing and analysis", value: "technical_testing" },
                    { label: "Television programming and broadcasting activities", value: "broadcasting" },
                    { label: "Temporary employment agency activities", value: "temp_employment" },
                    { label: "Tertiary education", value: "tertiary_education" },
                    { label: "Test drilling and boring", value: "test_drilling" },
                    { label: "Tour operator activities", value: "tour_operators" },
                    { label: "Translation and interpretation activities", value: "translation" },
                    { label: "Transmission of electricity", value: "electricity_transmission" },
                    { label: "Travel agency activities", value: "travel_agencies" },
                    { label: "Trusts, funds and similar financial entities", value: "trusts_funds" },
                    { label: "Urban and suburban passenger land transport", value: "public_transport" },
                    { label: "User missing", value: "user_missing" },
                    { label: "Warehousing and storage", value: "warehousing" },
                    { label: "Washing and (dry-)cleaning of textile and fur products", value: "laundry_cleaning" },
                    { label: "Web portals", value: "web_portals" },
                    { label: "Wholesale of food, beverages and tobacco", value: "wholesale_food" },
                    { label: "Wholesale of household goods", value: "wholesale_household" },
                    { label: "Wholesale of other machinery, equipment and supplies", value: "wholesale_machinery" },
                    { label: "Wholesale on fee or contract basis", value: "wholesale_contract" },
                    { label: "Wholesale trade of motor vehicle parts and accessories", value: "wholesale_vehicle_parts" },
                    { label: "Wired telecommunications activities", value: "telecommunications" }
                ]
            },
            {
                id: "occupation",
                type: "select",
                label: "Occupation",
                placeholder: "Choose an occupation",
                required: true,
                options: [
                    { label: "Accountants", value: "accountants" },
                    { label: "Accounting and bookkeeping clerks", value: "accounting_clerks" },
                    { label: "Accounting associate professionals", value: "accounting_associates" },
                    { label: "Actors", value: "actors" },
                    { label: "Administrative and executive secretaries", value: "secretaries" },
                    { label: "Advertising and marketing professionals", value: "marketing_professionals" },
                    { label: "Agricultural and industrial machinery mechanics and repairers", value: "machinery_mechanics" },
                    { label: "Applications programmers", value: "programmers" },
                    { label: "Butchers, fishmongers and related food preparers", value: "food_preparers" },
                    { label: "Buyers", value: "buyers" },
                    { label: "Cooks", value: "cooks" },
                    { label: "Craft and related workers not elsewhere classified", value: "craft_workers" },
                    { label: "Driving instructors", value: "driving_instructors" },
                    { label: "Early childhood educators", value: "educators" },
                    { label: "Film, stage and related directors and producers", value: "film_directors" },
                    { label: "Finance managers", value: "finance_managers" },
                    { label: "General office clerks", value: "office_clerks" },
                    { label: "Health care assistants", value: "health_assistants" },
                    { label: "Health professionals not elsewhere classified", value: "health_professionals" },
                    { label: "Human resource managers", value: "hr_managers" },
                    { label: "Locomotive engine drivers", value: "locomotive_drivers" },
                    { label: "Mail carriers and sorting clerks", value: "mail_carriers" },
                    { label: "Management and organisation analysts", value: "management_analysts" },
                    { label: "Mining and metallurgical technicians", value: "mining_technicians" },
                    { label: "Mining and quarrying labourers", value: "mining_labourers" },
                    { label: "Mining engineers, metallurgists and related professionals", value: "mining_engineers" },
                    { label: "Physicists and astronomers", value: "physicists" },
                    { label: "Physiotherapists", value: "physiotherapists" },
                    { label: "Physiotherapy technicians and assistants", value: "physiotherapy_technicians" },
                    { label: "Plastic products machine operators", value: "plastic_operators" },
                    { label: "Product graders and testers", value: "product_testers" },
                    { label: "Retail and wholesale trade managers", value: "trade_managers" },
                    { label: "Roofers", value: "roofers" },
                    { label: "Rubber products machine operators", value: "rubber_operators" },
                    { label: "Sales and marketing managers", value: "sales_managers" },
                    { label: "Senior government officials", value: "government_officials" },
                    { label: "Senior officials of special-interest organisations", value: "special_interest_officials" },
                    { label: "Service station attendants", value: "service_attendants" },
                    { label: "Services managers not elsewhere classified", value: "services_managers" },
                    { label: "Sports coaches, instructors and officials", value: "sports_coaches" },
                    { label: "Sports, recreation and cultural centre managers", value: "recreation_managers" },
                    { label: "Spray painters and varnishers", value: "painters" },
                    { label: "Stall and market salespersons", value: "market_salespersons" },
                    { label: "Stationary plant and machine operators not elsewhere classified", value: "machine_operators" },
                    { label: "Stock clerks", value: "stock_clerks" },
                    { label: "Systems analysts", value: "systems_analysts" },
                    { label: "Teaching professionals not elsewhere classified", value: "teaching_professionals" },
                    { label: "Technical and medical sales professionals", value: "technical_sales" },
                    { label: "Welders and flamecutters", value: "welders" },
                    { label: "Well drillers and borers and related workers", value: "well_drillers" },
                    { label: "Window cleaners", value: "window_cleaners" },
                    { label: "Wood processing plant operators", value: "wood_operators" },
                    { label: "Woodworking-machine tool setters and operators", value: "woodworking_operators" }
                ]
            },
            {
                id: "occupationLevel",
                type: "select",
                label: "Occupation Level",
                placeholder: "Choose an occupation level",
                required: true,
                options: [
                    { label: "Clerical support workers", value: "clerical_support" },
                    { label: "Craft and related trades workers", value: "craft_trades" },
                    { label: "Elementary occupations", value: "elementary_occupations" },
                    { label: "Managers", value: "managers" },
                    { label: "Plant and machine operators and assemblers", value: "plant_machine_operators" },
                    { label: "Professionals", value: "professionals" },
                    { label: "Service and sales workers", value: "service_sales" },
                    { label: "Skilled agricultural, forestry and fishery workers", value: "skilled_agricultural" },
                    { label: "Technicians and associate professionals", value: "technicians_associates" }
                ]
            }
        ]
    },
    {
        id: "step-3",
        stepNumber: 3,
        title: "Step 3",
        fields: [
            {
                id: "educationLevel",
                type: "select",
                label: "Education Level",
                required: true,
                options: [
                    { label: "Early childhood education", value: "early_childhood" },
                    { label: "Primary education", value: "primary" },
                    { label: "Primary education or 1st stage of basic education", value: "primary_basic" },
                    { label: "Lower secondary or 2nd stage of basic education", value: "lower_secondary" },
                    { label: "Lower secondary or 2nd stage of basic education 2A", value: "lower_secondary_2a" },
                    { label: "Upper secondary education", value: "upper_secondary" },
                    { label: "Upper secondary education 3A", value: "upper_secondary_3a" },
                    { label: "Upper secondary education 3C", value: "upper_secondary_3c" },
                    { label: "Post-secondary non-tertiary education", value: "post_secondary_non_tertiary" },
                    { label: "First stage of tertiary education", value: "first_tertiary" },
                    { label: "First stage of tertiary education 5A", value: "first_tertiary_5a" },
                    { label: "First stage of tertiary education 5B", value: "first_tertiary_5b" },
                    { label: "Second stage of tertiary education", value: "second_tertiary" },
                    { label: "Second stage of tertiary education (leading to an advanced research qualification)", value: "second_tertiary_research" },
                    { label: "No education", value: "no_education" }
                ]
            },
            {
                id: "yearsOfExperience",
                type: "select",
                label: "Years of Experience",
                required: true,
                options: []
            },
            {
                id: "companySize",
                type: "select",
                label: "Company Size",
                required: true,
                options: []
            }
        ]
    }
]

