/**
 * Salary Comparison Form Constants
 * 
 * Este archivo contiene todas las constantes utilizadas en el formulario de comparaciÃ³n salarial:
 * - Opciones de paÃ­ses
 * - Opciones de ocupaciones/profesiones
 * - Niveles de experiencia
 * - Labels de campos del formulario
 * - ConfiguraciÃ³n de pasos del wizard
 */

export const formSteps = [
    {
        stepNumber: 1,
        fields: [
            {
                id: "Country",
                type: "select",
                placeholder: "Choose a country",
                required: true,
                options: [
                    { label: "Belgium", value: "Belgium" },
                    { label: "Bulgaria", value: "Bulgaria" },

                    { label: "Cyprus", value: "Cyprus" },

                    { label: "Denmark", value: "Denmark" },

                    { label: "France", value: "France" },

                    { label: "Greece", value: "Greece" },

                    { label: "Italy", value: "Italy" },

                    { label: "Netherlands", value: "Netherlands" },
                    { label: "Portugal", value: "Portugal" },

                    { label: "Spain", value: "Spain" },

                    { label: "United Kingdom", value: "United Kingdom" },
                ],
            },
            {
                id: "Gender",
                type: "select",
                required: true,
                options: [
                    { label: "Male", value: "Male" },
                    { label: "Female", value: "Female" }

                ],
            },
            {
                id: "Monthly Wage",
                type: "number",
                required: true,
                placeholder: "Enter your monthly wage",
            },
        ],
    },
    {
        stepNumber: 2,
        fields: [
            {
                id: "Economic Activity",
                type: "select",
                placeholder: "Choose an economic activity",
                required: true,
                options: [
                    { label: "Accounting, bookkeeping and auditing activities; tax consultancy", value: "Accounting, bookkeeping and auditing activities; tax consultancy" },
                    { label: "Activities of amusement parks and theme parks", value: "Activities of amusement parks and theme parks" },
                    { label: "Activities of business and employers membership organisations", value: "Activities of business and employers membership organisations" },
                    { label: "Activities of call centres", value: "Activities of call centres" },
                    { label: "Activities of collection agencies and credit bureaus", value: "Activities of collection agencies and credit bureaus" },
                    { label: "Activities of employment placement agencies", value: "Activities of employment placement agencies" },
                    { label: "Activities of extraterritorial organisations and bodies", value: "Activities of extraterritorial organisations and bodies" },
                    { label: "Activities of head offices", value: "Activities of head offices" },
                    { label: "Activities of holding companies", value: "Activities of holding companies" },
                    { label: "Activities of households as employers of domestic personnel", value: "Activities of households as employers of domestic personnel" },
                    { label: "Activities of insurance agents and brokers", value: "Activities of insurance agents and brokers" },
                    { label: "Activities of other membership organisations n.e.c.", value: "Activities of other membership organisations n.e.c." },
                    { label: "Activities of political organisations", value: "Activities of political organisations" },
                    { label: "Activities of professional membership organisations", value: "Activities of professional membership organisations" },
                    { label: "Activities of religious organisations", value: "Activities of religious organisations" },
                    { label: "Activities of sports clubs", value: "Activities of sports clubs" },
                    { label: "Activities of trade unions", value: "Activities of trade unions" },
                    { label: "Administration of financial markets", value: "Administration of financial markets" },
                    { label: "Advertising agencies", value: "Advertising agencies" },
                    { label: "Air transport", value: "Air transport" },
                    { label: "Animal production", value: "Animal production" },
                    { label: "Aquaculture", value: "Aquaculture" },
                    { label: "Architectural activities", value: "Architectural activities" },
                    { label: "Artistic creation", value: "Artistic creation" },
                    { label: "Beverage serving activities", value: "Beverage serving activities" },
                    { label: "Binding and related services", value: "Binding and related services" },
                    { label: "Book publishing", value: "Book publishing" },
                    { label: "Botanical and zoological gardens and nature reserves activities", value: "Botanical and zoological gardens and nature reserves activities" },
                    { label: "Business and other management consultancy activities", value: "Business and other management consultancy activities" },
                    { label: "Buying and selling of own real estate", value: "Buying and selling of own real estate" },
                    { label: "Camping grounds, recreational vehicle parks and trailer parks", value: "Camping grounds, recreational vehicle parks and trailer parks" },
                    { label: "Cargo handling", value: "Cargo handling" },
                    { label: "Central banking", value: "Central banking" },
                    { label: "Child day-care activities", value: "Child day-care activities" },
                    { label: "Collection of hazardous waste", value: "Collection of hazardous waste" },
                    { label: "Collection of non-hazardous waste", value: "Collection of non-hazardous waste" },
                    { label: "Combined facilities support activities", value: "Combined facilities support activities" },
                    { label: "Combined office administrative service activities", value: "Combined office administrative service activities" },
                    { label: "Computer consultancy activities", value: "Computer consultancy activities" },
                    { label: "Computer facilities management activities", value: "Computer facilities management activities" },
                    { label: "Computer programming activities", value: "Computer programming activities" },
                    { label: "Computer programming, consultancy and related activities", value: "Computer programming, consultancy and related activities" },
                    { label: "Compulsory social security activities", value: "Compulsory social security activities" },
                    { label: "Construction of bridges and tunnels", value: "Construction of bridges and tunnels" },
                    { label: "Construction of railways and underground railways", value: "Construction of railways and underground railways" },
                    { label: "Construction of residential and non-residential buildings", value: "Construction of residential and non-residential buildings" },
                    { label: "Construction of roads and motorways", value: "Construction of roads and motorways" },
                    { label: "Construction of utility projects for electricity and telecommunications", value: "Construction of utility projects for electricity and telecommunications" },
                    { label: "Construction of utility projects for fluids", value: "Construction of utility projects for fluids" },
                    { label: "Construction of water projects", value: "Construction of water projects" },
                    { label: "Cultural education", value: "Cultural education" },
                    { label: "Data processing, hosting and related activities", value: "Data processing, hosting and related activities" },
                    { label: "Defence activities", value: "Defence activities" },
                    { label: "Demolition and site preparation", value: "Demolition and site preparation" },
                    { label: "Dental practice activities", value: "Dental practice activities" },
                    { label: "Development of building projects", value: "Development of building projects" },
                    { label: "Dispensing chemist in specialised stores", value: "Dispensing chemist in specialised stores" },
                    { label: "Distribution of electricity", value: "Distribution of electricity" },
                    { label: "Distribution of gaseous fuels through mains", value: "Distribution of gaseous fuels through mains" },
                    { label: "Driving school activities", value: "Driving school activities" },
                    { label: "Educational support activities", value: "Educational support activities" },
                    { label: "Electrical installation", value: "Electrical installation" },
                    { label: "Electricity, gas, steam and air conditioning supply", value: "Electricity, gas, steam and air conditioning supply" },
                    { label: "Engineering activities and related technical consultancy", value: "Engineering activities and related technical consultancy" },
                    { label: "Event catering activities", value: "Event catering activities" },
                    { label: "Extraction of crude petroleum", value: "Extraction of crude petroleum" },
                    { label: "Extraction of natural gas", value: "Extraction of natural gas" },
                    { label: "Extraction of salt", value: "Extraction of salt" },
                    { label: "Financial leasing", value: "Financial leasing" },
                    { label: "Fire service activities", value: "Fire service activities" },
                    { label: "Fishing", value: "Fishing" },
                    { label: "Fitness facilities", value: "Fitness facilities" },
                    { label: "Floor and wall covering", value: "Floor and wall covering" },
                    { label: "Foreign affairs", value: "Foreign affairs" },
                    { label: "Forestry and logging", value: "Forestry and logging" },
                    { label: "Freight air transport", value: "Freight air transport" },
                    { label: "Freight rail transport", value: "Freight rail transport" },
                    { label: "Freight transport by road", value: "Freight transport by road" },
                    { label: "Fund management activities", value: "Fund management activities" },
                    { label: "Funeral and related activities", value: "Funeral and related activities" },
                    { label: "Gambling and betting activities", value: "Gambling and betting activities" },
                    { label: "General cleaning of buildings", value: "General cleaning of buildings" },
                    { label: "General medical practice activities", value: "General medical practice activities" },
                    { label: "General public administration activities", value: "General public administration activities" },
                    { label: "General secondary education", value: "General secondary education" },
                    { label: "Growing of non-perennial crops", value: "Growing of non-perennial crops" },
                    { label: "Growing of perennial crops", value: "Growing of perennial crops" },
                    { label: "Hairdressing and other beauty treatment", value: "Hairdressing and other beauty treatment" },
                    { label: "Holiday and other short-stay accommodation", value: "Holiday and other short-stay accommodation" },
                    { label: "Homework: assembly work", value: "Homework: assembly work" },
                    { label: "Hospital activities", value: "Hospital activities" },
                    { label: "Hotels and similar accommodation", value: "Hotels and similar accommodation" },
                    { label: "Hunting, trapping and related service activities", value: "Hunting, trapping and related service activities" },
                    { label: "Information service activities", value: "Information service activities" },
                    { label: "Inland freight water transport", value: "Inland freight water transport" },
                    { label: "Inland passenger water transport", value: "Inland passenger water transport" },
                    { label: "Investigation activities", value: "Investigation activities" },
                    { label: "Joinery installation", value: "Joinery installation" },
                    { label: "Justice and judicial activities", value: "Justice and judicial activities" },
                    { label: "Landscape service activities", value: "Landscape service activities" },
                    { label: "Leasing of intellectual property and similar products, except copyrighted works", value: "Leasing of intellectual property and similar products, except copyrighted works" },
                    { label: "Legal activities", value: "Legal activities" },
                    { label: "Library and archives activities", value: "Library and archives activities" },
                    { label: "Life insurance", value: "Life insurance" },
                    { label: "Maintenance and repair of motor vehicles", value: "Maintenance and repair of motor vehicles" },
                    { label: "Management of real estate on a fee or contract basis", value: "Management of real estate on a fee or contract basis" },
                    { label: "Management of real estate on fee or contract basis", value: "Management of real estate on fee or contract basis" },
                    { label: "Manufacture of base metals", value: "Manufacture of base metals" },
                    { label: "Manufacture of basic metals", value: "Manufacture of basic metals" },
                    { label: "Manufacture of basic pharmaceutical products and pharmaceutical preparations", value: "Manufacture of basic pharmaceutical products and pharmaceutical preparations" },
                    { label: "Manufacture of beverages", value: "Manufacture of beverages" },
                    { label: "Manufacture of cement, lime and plaster", value: "Manufacture of cement, lime and plaster" },
                    { label: "Manufacture of chemicals and chemical products", value: "Manufacture of chemicals and chemical products" },
                    { label: "Manufacture of coke and refined petroleum products", value: "Manufacture of coke and refined petroleum products" },
                    { label: "Manufacture of computer, electronic and optical products", value: "Manufacture of computer, electronic and optical products" },
                    { label: "Manufacture of electrical equipment", value: "Manufacture of electrical equipment" },
                    { label: "Manufacture of fabricated metal products", value: "Manufacture of fabricated metal products" },
                    { label: "Manufacture of fabricated metal products, except machinery and equipment", value: "Manufacture of fabricated metal products, except machinery and equipment" },
                    { label: "Manufacture of food products", value: "Manufacture of food products" },
                    { label: "Manufacture of furniture", value: "Manufacture of furniture" },
                    { label: "Manufacture of gas", value: "Manufacture of gas" },
                    { label: "Manufacture of leather and related products", value: "Manufacture of leather and related products" },
                    { label: "Manufacture of machinery and equipment", value: "Manufacture of machinery and equipment" },
                    { label: "Manufacture of machinery and equipment n.e.c.", value: "Manufacture of machinery and equipment n.e.c." },
                    { label: "Manufacture of motor vehicles, trailers and semi-trailers", value: "Manufacture of motor vehicles, trailers and semi-trailers" },
                    { label: "Manufacture of other non-metallic mineral products", value: "Manufacture of other non-metallic mineral products" },
                    { label: "Manufacture of other transport equipment", value: "Manufacture of other transport equipment" },
                    { label: "Manufacture of paper and paper products", value: "Manufacture of paper and paper products" },
                    { label: "Manufacture of rubber and plastic products", value: "Manufacture of rubber and plastic products" },
                    { label: "Manufacture of textiles", value: "Manufacture of textiles" },
                    { label: "Manufacture of tobacco products", value: "Manufacture of tobacco products" },
                    { label: "Manufacture of wearing apparel", value: "Manufacture of wearing apparel" },
                    { label: "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials", value: "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials" },
                    { label: "Manufacture of wood and products of wood and cork", value: "Manufacture of wood and products of wood and cork" },
                    { label: "Market research and public opinion polling", value: "Market research and public opinion polling" },
                    { label: "Media representation", value: "Media representation" },
                    { label: "Mining of chemical and fertiliser minerals", value: "Mining of chemical and fertiliser minerals" },
                    { label: "Mining of iron ores", value: "Mining of iron ores" },
                    { label: "Mining of lignite", value: "Mining of lignite" },
                    { label: "Mining of other non-ferrous metal ores", value: "Mining of other non-ferrous metal ores" },
                    { label: "Mining of uranium and thorium ores", value: "Mining of uranium and thorium ores" },
                    { label: "Missing (Drop out)", value: "Missing (Drop out)" },
                    { label: "Missing (Mapping not available)", value: "Missing (Mapping not available)" },
                    { label: "Missing (Reason unknown)", value: "Missing (Reason unknown)" },
                    { label: "Mixed farming", value: "Mixed farming" },
                    { label: "Motion picture projection activities", value: "Motion picture projection activities" },
                    { label: "Motion picture, video and television programme distribution activities", value: "Motion picture, video and television programme distribution activities" },
                    { label: "Motion picture, video and television programme post-production activities", value: "Motion picture, video and television programme post-production activities" },
                    { label: "Motion picture, video and television programme production activities", value: "Motion picture, video and television programme production activities" },
                    { label: "Museums activities", value: "Museums activities" },
                    { label: "News agency activities", value: "News agency activities" },
                    { label: "Non-life insurance", value: "Non-life insurance" },
                    { label: "Non-specialised wholesale trade", value: "Non-specialised wholesale trade" },
                    { label: "Not asked (Skipped)", value: "Not asked (Skipped)" },
                    { label: "Operation of arts facilities", value: "Operation of arts facilities" },
                    { label: "Operation of gravel and sand pits; mining of clays and kaolin", value: "Operation of gravel and sand pits; mining of clays and kaolin" },
                    { label: "Operation of historical sites and buildings and similar visitor attractions", value: "Operation of historical sites and buildings and similar visitor attractions" },
                    { label: "Operation of sports facilities", value: "Operation of sports facilities" },
                    { label: "Organisation of conventions and trade shows", value: "Organisation of conventions and trade shows" },
                    { label: "Other accommodation", value: "Other accommodation" },
                    { label: "Other activities auxiliary to financial services", value: "Other activities auxiliary to financial services" },
                    { label: "Other activities auxiliary to financial services, except insurance and pension funding", value: "Other activities auxiliary to financial services, except insurance and pension funding" },
                    { label: "Other amusement and recreation activities", value: "Other amusement and recreation activities" },
                    { label: "Other building and industrial cleaning activities", value: "Other building and industrial cleaning activities" },
                    { label: "Other cleaning activities", value: "Other cleaning activities" },
                    { label: "Other construction installation", value: "Other construction installation" },
                    { label: "Other credit granting", value: "Other credit granting" },
                    { label: "Other education", value: "Other education" },
                    { label: "Other education n.e.c.", value: "Other education n.e.c." },
                    { label: "Other financial service activities, except insurance and pension funding n.e.c.", value: "Other financial service activities, except insurance and pension funding n.e.c." },
                    { label: "Other food service activities", value: "Other food service activities" },
                    { label: "Other human health activities", value: "Other human health activities" },
                    { label: "Other human resources provision", value: "Other human resources provision" },
                    { label: "Other information technology and computer service activities", value: "Other information technology and computer service activities" },
                    { label: "Other manufacturing", value: "Other manufacturing" },
                    { label: "Other manufacturing n.e.c.", value: "Other manufacturing n.e.c." },
                    { label: "Other mining and quarrying", value: "Other mining and quarrying" },
                    { label: "Other mining and quarrying n.e.c.", value: "Other mining and quarrying n.e.c." },
                    { label: "Other monetary intermediation", value: "Other monetary intermediation" },
                    { label: "Other personal service activities", value: "Other personal service activities" },
                    { label: "Other personal service activities n.e.c.", value: "Other personal service activities n.e.c." },
                    { label: "Other postal and courier activities", value: "Other postal and courier activities" },
                    { label: "Other printing", value: "Other printing" },
                    { label: "Other professional, scientific and technical activities", value: "Other professional, scientific and technical activities" },
                    { label: "Other professional, scientific and technical activities n.e.c.", value: "Other professional, scientific and technical activities n.e.c." },
                    { label: "Other research and experimental development", value: "Other research and experimental development" },
                    { label: "Other research and experimental development on natural sciences and engineering", value: "Other research and experimental development on natural sciences and engineering" },
                    { label: "Other social work activities without accommodation n.e.c.", value: "Other social work activities without accommodation n.e.c." },
                    { label: "Other software publishing", value: "Other software publishing" },
                    { label: "Other specialised wholesale", value: "Other specialised wholesale" },
                    { label: "Other sports activities", value: "Other sports activities" },
                    { label: "Packaging activities", value: "Packaging activities" },
                    { label: "Painting and glazing", value: "Painting and glazing" },
                    { label: "Passenger air transport", value: "Passenger air transport" },
                    { label: "Passenger rail transport, interurban", value: "Passenger rail transport, interurban" },
                    { label: "Pension funding", value: "Pension funding" },
                    { label: "Performing arts", value: "Performing arts" },
                    { label: "Photocopying, document preparation and other specialised office support activities", value: "Photocopying, document preparation and other specialised office support activities" },
                    { label: "Photographic activities", value: "Photographic activities" },
                    { label: "Photography activities", value: "Photography activities" },
                    { label: "Physical well-being activities", value: "Physical well-being activities" },
                    { label: "Plant propagation", value: "Plant propagation" },
                    { label: "Plastering", value: "Plastering" },
                    { label: "Plumbing, heat and air-conditioning installation", value: "Plumbing, heat and air-conditioning installation" },
                    { label: "Post-secondary non-tertiary education", value: "Post-secondary non-tertiary education" },
                    { label: "Postal activities under universal service obligation", value: "Postal activities under universal service obligation" },
                    { label: "Postal and courier activities", value: "Postal and courier activities" },
                    { label: "Pre-press and pre-media services", value: "Pre-press and pre-media services" },
                    { label: "Pre-primary education", value: "Pre-primary education" },
                    { label: "Primary education", value: "Primary education" },
                    { label: "Printing of newspapers", value: "Printing of newspapers" },
                    { label: "Private security activities", value: "Private security activities" },
                    { label: "Production of electricity", value: "Production of electricity" },
                    { label: "Public order and safety activities", value: "Public order and safety activities" },
                    { label: "Public relations and communication activities", value: "Public relations and communication activities" },
                    { label: "Publishing of computer games", value: "Publishing of computer games" },
                    { label: "Publishing of journals and periodicals", value: "Publishing of journals and periodicals" },
                    { label: "Publishing of newspapers", value: "Publishing of newspapers" },
                    { label: "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate", value: "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate" },
                    { label: "Radio broadcasting", value: "Radio broadcasting" },
                    { label: "Real estate agencies", value: "Real estate agencies" },
                    { label: "Recovery of sorted materials", value: "Recovery of sorted materials" },
                    { label: "Regulation of and contribution to more efficient operation of businesses", value: "Regulation of and contribution to more efficient operation of businesses" },
                    { label: "Regulation of health care, education and social services", value: "Regulation of health care, education and social services" },
                    { label: "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security", value: "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security" },
                    { label: "Reinsurance", value: "Reinsurance" },
                    { label: "Remediation activities and other waste management services", value: "Remediation activities and other waste management services" },
                    { label: "Removal services", value: "Removal services" },
                    { label: "Rental and leasing of agricultural machinery and equipment", value: "Rental and leasing of agricultural machinery and equipment" },
                    { label: "Rental and leasing of cars and light motor vehicles", value: "Rental and leasing of cars and light motor vehicles" },
                    { label: "Rental and leasing of construction and civil engineering machinery and equipment", value: "Rental and leasing of construction and civil engineering machinery and equipment" },
                    { label: "Rental and leasing of office machinery and equipment (including computers)", value: "Rental and leasing of office machinery and equipment (including computers)" },
                    { label: "Rental and leasing of other machinery, equipment and tangible goods n.e.c.", value: "Rental and leasing of other machinery, equipment and tangible goods n.e.c." },
                    { label: "Rental and leasing of personal and household goods", value: "Rental and leasing of personal and household goods" },
                    { label: "Rental and operating of own or leased real estate", value: "Rental and operating of own or leased real estate" },
                    { label: "Repair and installation of machinery and equipment", value: "Repair and installation of machinery and equipment" },
                    { label: "Repair of computers and communication equipment", value: "Repair of computers and communication equipment" },
                    { label: "Repair of personal and household goods", value: "Repair of personal and household goods" },
                    { label: "Research and experimental development on biotechnology", value: "Research and experimental development on biotechnology" },
                    { label: "Research and experimental development on social sciences and humanities", value: "Research and experimental development on social sciences and humanities" },
                    { label: "Residential care activities", value: "Residential care activities" },
                    { label: "Residential care activities for mental retardation, mental health and substance abuse", value: "Residential care activities for mental retardation, mental health and substance abuse" },
                    { label: "Residential care activities for the elderly and disabled", value: "Residential care activities for the elderly and disabled" },
                    { label: "Residential nursing care activities", value: "Residential nursing care activities" },
                    { label: "Restaurants and mobile food service activities", value: "Restaurants and mobile food service activities" },
                    { label: "Retail sale in non-specialised stores", value: "Retail sale in non-specialised stores" },
                    { label: "Retail sale of automotive fuel", value: "Retail sale of automotive fuel" },
                    { label: "Retail sale of automotive fuel in specialised stores", value: "Retail sale of automotive fuel in specialised stores" },
                    { label: "Retail sale of books in specialised stores", value: "Retail sale of books in specialised stores" },
                    { label: "Retail sale of carpets, rugs, wall and floor coverings in specialised stores", value: "Retail sale of carpets, rugs, wall and floor coverings in specialised stores" },
                    { label: "Retail sale of clothing", value: "Retail sale of clothing" },
                    { label: "Retail sale of clothing in specialised stores", value: "Retail sale of clothing in specialised stores" },
                    { label: "Retail sale of cosmetic and toilet articles in specialised stores", value: "Retail sale of cosmetic and toilet articles in specialised stores" },
                    { label: "Retail sale of cosmetics and toilet articles", value: "Retail sale of cosmetics and toilet articles" },
                    { label: "Retail sale of electrical household appliances in specialised stores", value: "Retail sale of electrical household appliances in specialised stores" },
                    { label: "Retail sale of flowers, plants, seeds", value: "Retail sale of flowers, plants, seeds" },
                    { label: "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores", value: "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores" },
                    { label: "Retail sale of food, beverages and tobacco", value: "Retail sale of food, beverages and tobacco" },
                    { label: "Retail sale of food, beverages and tobacco in specialised stores", value: "Retail sale of food, beverages and tobacco in specialised stores" },
                    { label: "Retail sale of footwear and leather goods", value: "Retail sale of footwear and leather goods" },
                    { label: "Retail sale of footwear and leather goods in specialised stores", value: "Retail sale of footwear and leather goods in specialised stores" },
                    { label: "Retail sale of furniture and household articles", value: "Retail sale of furniture and household articles" },
                    { label: "Retail sale of furniture, lighting equipment and other household articles in specialised stores", value: "Retail sale of furniture, lighting equipment and other household articles in specialised stores" },
                    { label: "Retail sale of games and toys in specialised stores", value: "Retail sale of games and toys in specialised stores" },
                    { label: "Retail sale of hardware, paints and glass in specialised stores", value: "Retail sale of hardware, paints and glass in specialised stores" },
                    { label: "Retail sale of information and communication equipment in specialised stores", value: "Retail sale of information and communication equipment in specialised stores" },
                    { label: "Retail sale of medical and orthopaedic goods", value: "Retail sale of medical and orthopaedic goods" },
                    { label: "Retail sale of medical and orthopaedic goods in specialised stores", value: "Retail sale of medical and orthopaedic goods in specialised stores" },
                    { label: "Retail sale of newspapers and stationery", value: "Retail sale of newspapers and stationery" },
                    { label: "Retail sale of newspapers and stationery in specialised stores", value: "Retail sale of newspapers and stationery in specialised stores" },
                    { label: "Retail sale of second-hand goods", value: "Retail sale of second-hand goods" },
                    { label: "Retail sale of second-hand goods in stores", value: "Retail sale of second-hand goods in stores" },
                    { label: "Retail sale of sporting equipment", value: "Retail sale of sporting equipment" },
                    { label: "Retail sale of sporting equipment in specialised stores", value: "Retail sale of sporting equipment in specialised stores" },
                    { label: "Retail sale of textiles", value: "Retail sale of textiles" },
                    { label: "Retail sale of textiles in specialised stores", value: "Retail sale of textiles in specialised stores" },
                    { label: "Retail sale of watches and jewellery", value: "Retail sale of watches and jewellery" },
                    { label: "Retail sale of watches and jewellery in specialised stores", value: "Retail sale of watches and jewellery in specialised stores" },
                    { label: "Retail sale via mail order houses or via Internet", value: "Retail sale via mail order houses or via Internet" },
                    { label: "Retail sale via mail order or internet", value: "Retail sale via mail order or internet" },
                    { label: "Retail sale via stalls and markets", value: "Retail sale via stalls and markets" },
                    { label: "Retail trade of motor vehicle parts and accessories", value: "Retail trade of motor vehicle parts and accessories" },
                    { label: "Retail trade, except of motor vehicles and motorcycles", value: "Retail trade, except of motor vehicles and motorcycles" },
                    { label: "Risk and damage evaluation", value: "Risk and damage evaluation" },
                    { label: "Roofing activities", value: "Roofing activities" },
                    { label: "Sale of cars and light motor vehicles", value: "Sale of cars and light motor vehicles" },
                    { label: "Sale of other motor vehicles", value: "Sale of other motor vehicles" },
                    { label: "Sale, maintenance and repair of motorcycles and related parts and accessories", value: "Sale, maintenance and repair of motorcycles and related parts and accessories" },
                    { label: "Satellite telecommunications activities", value: "Satellite telecommunications activities" },
                    { label: "Sea and coastal freight water transport", value: "Sea and coastal freight water transport" },
                    { label: "Sea and coastal passenger water transport", value: "Sea and coastal passenger water transport" },
                    { label: "Security and commodity contracts brokerage", value: "Security and commodity contracts brokerage" },
                    { label: "Security systems service activities", value: "Security systems service activities" },
                    { label: "Service activities incidental to air transportation", value: "Service activities incidental to air transportation" },
                    { label: "Service activities incidental to land transportation", value: "Service activities incidental to land transportation" },
                    { label: "Service activities incidental to water transportation", value: "Service activities incidental to water transportation" },
                    { label: "Sewerage", value: "Sewerage" },
                    { label: "Social work activities for the elderly and disabled", value: "Social work activities for the elderly and disabled" },
                    { label: "Social work activities without accommodation for the elderly and disabled", value: "Social work activities without accommodation for the elderly and disabled" },
                    { label: "Sound recording and music publishing activities", value: "Sound recording and music publishing activities" },
                    { label: "Space transport", value: "Space transport" },
                    { label: "Specialised design activities", value: "Specialised design activities" },
                    { label: "Specialist medical practice activities", value: "Specialist medical practice activities" },
                    { label: "Sports and recreation education", value: "Sports and recreation education" },
                    { label: "Steam and air conditioning supply", value: "Steam and air conditioning supply" },
                    { label: "Support activities for other mining and quarrying", value: "Support activities for other mining and quarrying" },
                    { label: "Support activities for petroleum and natural gas extraction", value: "Support activities for petroleum and natural gas extraction" },
                    { label: "Support activities to agriculture", value: "Support activities to agriculture" },
                    { label: "Support activities to agriculture and post-harvest crop activities", value: "Support activities to agriculture and post-harvest crop activities" },
                    { label: "Support activities to performing arts", value: "Support activities to performing arts" },
                    { label: "Support services to forestry", value: "Support services to forestry" },
                    { label: "Taxi operation", value: "Taxi operation" },
                    { label: "Technical and vocational secondary education", value: "Technical and vocational secondary education" },
                    { label: "Technical testing and analysis", value: "Technical testing and analysis" },
                    { label: "Television programming and broadcasting activities", value: "Television programming and broadcasting activities" },
                    { label: "Temporary employment agency activities", value: "Temporary employment agency activities" },
                    { label: "Tertiary education", value: "Tertiary education" },
                    { label: "Test drilling and boring", value: "Test drilling and boring" },
                    { label: "Tour operator activities", value: "Tour operator activities" },
                    { label: "Translation and interpretation activities", value: "Translation and interpretation activities" },
                    { label: "Transmission of electricity", value: "Transmission of electricity" },
                    { label: "Transport via pipeline", value: "Transport via pipeline" },
                    { label: "Travel agency activities", value: "Travel agency activities" },
                    { label: "Treatment and disposal of hazardous waste", value: "Treatment and disposal of hazardous waste" },
                    { label: "Treatment and disposal of non-hazardous waste", value: "Treatment and disposal of non-hazardous waste" },
                    { label: "Trusts, funds and similar financial entities", value: "Trusts, funds and similar financial entities" },
                    { label: "U Activities of extraterritorial organisations and bodies", value: "U Activities of extraterritorial organisations and bodies" },
                    { label: "Undifferentiated service-producing activities of private households for own use", value: "Undifferentiated service-producing activities of private households for own use" },
                    { label: "Urban and suburban passenger land transport", value: "Urban and suburban passenger land transport" },
                    { label: "User missing", value: "User missing" },
                    { label: "Veterinary activities", value: "Veterinary activities" },
                    { label: "Warehousing and storage", value: "Warehousing and storage" },
                    { label: "Washing and (dry-)cleaning of textile and fur products", value: "Washing and (dry-)cleaning of textile and fur products" },
                    { label: "Water collection, treatment and supply", value: "Water collection, treatment and supply" },
                    { label: "Water transport", value: "Water transport" },
                    { label: "Web portals", value: "Web portals" },
                    { label: "Wholesale of agricultural raw materials and live animals", value: "Wholesale of agricultural raw materials and live animals" },
                    { label: "Wholesale of food, beverages and tobacco", value: "Wholesale of food, beverages and tobacco" },
                    { label: "Wholesale of household goods", value: "Wholesale of household goods" },
                    { label: "Wholesale of information and communication equipment", value: "Wholesale of information and communication equipment" },
                    { label: "Wholesale of other machinery, equipment and supplies", value: "Wholesale of other machinery, equipment and supplies" },
                    { label: "Wholesale on a fee or contract basis", value: "Wholesale on a fee or contract basis" },
                    { label: "Wholesale on fee or contract basis", value: "Wholesale on fee or contract basis" },
                    { label: "Wholesale trade of motor vehicle parts and accessories", value: "Wholesale trade of motor vehicle parts and accessories" },
                    { label: "Wired telecommunications activities", value: "Wired telecommunications activities" },
                    { label: "Wireless telecommunications activities", value: "Wireless telecommunications activities" },
                ],
            },
            {
                id: "Occupation",
                type: "select",
                placeholder: "Choose an occupation",
                required: true,
                options: [
                    { label: "Accountants", value: "Accountants" },
                    {
                        label: "Accounting and bookkeeping clerks", value: "Accounting and bookkeeping clerks",
                    },
                    {
                        label: "Accounting associate professionals", value: "Accounting associate professionals",
                    },
                    { label: "Actors", value: "Actors" },
                    {
                        label: "Administrative and executive secretaries", value: "Administrative and executive secretaries",
                    },
                    {
                        label: "Advertising and marketing professionals", value: "Advertising and marketing professionals",
                    },
                    {
                        label: "Agricultural and industrial machinery mechanics and repairers", value: "Agricultural and industrial machinery mechanics and repairers",
                    },
                    { label: "Applications programmers", value: "Applications programmers" },
                    {
                        label: "Butchers, fishmongers and related food preparers", value: "Butchers, fishmongers and related food preparers",
                    },
                    { label: "Buyers", value: "Buyers" },
                    { label: "Cooks", value: "Cooks" },
                    {
                        label: "Craft and related workers not elsewhere classified", value: "Craft and related workers not elsewhere classified",
                    },
                    { label: "Driving instructors", value: "Driving instructors" },
                    { label: "Early childhood educators", value: "Early childhood educators" },
                    {
                        label: "Film, stage and related directors and producers", value: "Film, stage and related directors and producers",
                    },
                    { label: "Finance managers", value: "Finance managers" },
                    { label: "General office clerks", value: "General office clerks" },
                    { label: "Health care assistants", value: "Health care assistants" },
                    {
                        label: "Health professionals not elsewhere classified", value: "Health professionals not elsewhere classified",
                    },
                    { label: "Human resource managers", value: "Human resource managers" },
                    { label: "Locomotive engine drivers", value: "Locomotive engine drivers" },
                    { label: "Mail carriers and sorting clerks", value: "Mail carriers and sorting clerks" },
                    {
                        label: "Management and organisation analysts", value: "Management and organisation analysts",
                    },
                    {
                        label: "Mining and metallurgical technicians", value: "Mining and metallurgical technicians",
                    },
                    {
                        label: "Mining and quarrying labourers", value: "Mining and quarrying labourers",
                    },
                    {
                        label: "Mining engineers, metallurgists and related professionals", value: "Mining engineers, metallurgists and related professionals",
                    },
                    { label: "Physicists and astronomers", value: "Physicists and astronomers" },
                    { label: "Physiotherapists", value: "Physiotherapists" },
                    {
                        label: "Physiotherapy technicians and assistants", value: "Physiotherapy technicians and assistants",
                    },
                    {
                        label: "Plastic products machine operators", value: "Plastic products machine operators",
                    },
                    { label: "Product graders and testers", value: "Product graders and testers" },
                    {
                        label: "Retail and wholesale trade managers", value: "Retail and wholesale trade managers",
                    },
                    { label: "Roofers", value: "Roofers" },
                    {
                        label: "Rubber products machine operators", value: "Rubber products machine operators",
                    },
                    { label: "Sales and marketing managers", value: "Sales and marketing managers" },
                    {
                        label: "Senior government officials", value: "Senior government officials",
                    },
                    {
                        label: "Senior officials of special-interest organisations", value: "Senior officials of special-interest organisations",
                    },
                    { label: "Service station attendants", value: "Service station attendants" },
                    {
                        label: "Services managers not elsewhere classified", value: "Services managers not elsewhere classified",
                    },
                    {
                        label: "Sports coaches, instructors and officials", value: "Sports coaches, instructors and officials",
                    },
                    {
                        label: "Sports, recreation and cultural centre managers", value: "Sports, recreation and cultural centre managers",
                    },
                    { label: "Spray painters and varnishers", value: "Spray painters and varnishers" },
                    {
                        label: "Stall and market salespersons", value: "Stall and market salespersons",
                    },
                    {
                        label: "Stationary plant and machine operators not elsewhere classified", value: "Stationary plant and machine operators not elsewhere classified",
                    },
                    { label: "Stock clerks", value: "Stock clerks" },
                    { label: "Systems analysts", value: "Systems analysts" },
                    {
                        label: "Teaching professionals not elsewhere classified", value: "Teaching professionals not elsewhere classified",
                    },
                    {
                        label: "Technical and medical sales professionals", value: "Technical and medical sales professionals",
                    },
                    { label: "Welders and flamecutters", value: "Welders and flamecutters" },
                    {
                        label: "Well drillers and borers and related workers", value: "Well drillers and borers and related workers",
                    },
                    { label: "Window cleaners", value: "Window cleaners" },
                    { label: "Wood processing plant operators", value: "Wood processing plant operators" },
                    {
                        label: "Woodworking-machine tool setters and operators", value: "Woodworking-machine tool setters and operators",
                    },
                ],
            },
            {
                id: "Occupation Level",
                type: "select",
                placeholder: "Choose an occupation level",
                required: true,
                options: [
                    {
                        label: "Armed forces occupations", value: "Armed forces occupations",
                    },
                    { label: "Clerical support workers", value: "Clerical support workers" },
                    { label: "Craft and related trades workers", value: "Craft and related trades workers" },
                    { label: "Elementary occupations", value: "Elementary occupations" },
                    { label: "Managers", value: "Managers" },
                    {
                        label: "Plant and machine operators and assemblers", value: "Plant and machine operators and assemblers",
                    },
                    { label: "Professionals", value: "Professionals" },
                    { label: "Service and sales workers", value: "Service and sales workers" },
                    {
                        label: "Skilled agricultural, forestry and fishery workers", value: "Skilled agricultural, forestry and fishery workers",
                    },
                    {
                        label: "Technicians and associate professionals", value: "Technicians and associate professionals",
                    },
                ],
            },
        ],
    },
    {
        stepNumber: 3,
        fields: [
            {
                id: "Education Level",
                type: "select",
                required: true,
                options: [
                    { label: "Early childhood education", value: "Early childhood education" },
                    { label: "Primary education", value: "Primary education" },
                    {
                        label: "Primary education or 1st stage of basic education", value: "Primary education or 1st stage of basic education",
                    },
                    {
                        label: "Lower secondary or 2nd stage of basic education", value: "Lower secondary or 2nd stage of basic education",
                    },
                    {
                        label: "Lower secondary or 2nd stage of basic education 2A", value: "Lower secondary or 2nd stage of basic education 2A",
                    },
                    { label: "Upper secondary education", value: "Upper secondary education" },
                    {
                        label: "Upper secondary education 3A", value: "Upper secondary education 3A",
                    },
                    {
                        label: "Upper secondary education 3C", value: "Upper secondary education 3C",
                    },
                    {
                        label: "Post-secondary non-tertiary education", value: "Post-secondary non-tertiary education",
                    },
                    {
                        label: "First stage of tertiary education", value: "First stage of tertiary education",
                    },
                    {
                        label: "First stage of tertiary education 5A", value: "First stage of tertiary education 5A",
                    },
                    {
                        label: "First stage of tertiary education 5B", value: "First stage of tertiary education 5B",
                    },
                    {
                        label: "Second stage of tertiary education", value: "Second stage of tertiary education",
                    },
                    {
                        label: "Second stage of tertiary education (leading to an advanced research qualification)", value: "Second stage of tertiary education (leading to an advanced research qualification)",
                    },
                    { label: "No education", value: "No education" },
                ],
            },
            {
                id: "Years Of Experience",
                type: "select",
                required: true,
                options: [
                    { label: "Less than 1 year", value: "Less than 1 year" },
                    { label: "1-2 years", value: "1-2 years" },
                    { label: "3-5 years", value: "3-5 years" },
                    { label: "6-10 years", value: "6-10 years" },
                    { label: "11-15 years", value: "11-15 years" },
                    { label: "16-20 years", value: "16-20 years" },
                    { label: "More than 20 years", value: "More than 20 years" },
                ],
            },
            {
                id: "Company Size",
                type: "select",
                required: true,
                options: [
                    { label: "1-10 employees", value: "1-10 employees" },
                    { label: "11-50 employees", value: "11-50 employees" },
                    { label: "51-200 employees", value: "51-200 employees" },
                    { label: "201-500 employees", value: "201-500 employees" },
                    { label: "501-1000 employees", value: "501-1000 employees" },
                    { label: "1001-5000 employees", value: "1001-5000 employees" },
                    { label: "More than 5000 employees", value: "More than 5000 employees" },
                ],
            },
        ],
    },
];

/** Columnas de TABLE_0 que solicitamos en el select de la query PostgREST */
export const SUPABASE_SELECT_COLUMNS = [
    'Country',
    'Gender',
    'Occupation',
    'Occupation Level',
    'Economic Activity',
    'Education Level',
    'Monthly Wage',
    'Year',
] as const;

const countryField = formSteps
    .flatMap((step) => step.fields)
    .find((field) => field.id === 'Country');

export const VALID_COUNTRIES = new Set(
    (countryField?.options ?? []).map((option) => option.value),
);


